//PRODUCTS
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";

//CLIENTS
const GET_CLIENTS = "GET_CLIENTS";
const GET_CLIENT_DETAIL = "GET_CLIENT_DETAIL";

//USERS
const REGISTER_USER = "REGISTER_USER";

export {
  GET_PRODUCTS,
  GET_CLIENTS,
  GET_CLIENT_DETAIL,
  GET_PRODUCT_DETAIL,
  REGISTER_USER,
};
